[package]
name = "connector-source-mqtt"
group = "infinyon"
version = "0.5.2"
apiVersion = "0.1.0"
minFluvio = "0.10.0"
description = "My protocol"
license = "Apache-2.0"
repository = "https://github.com/mygroup/myconnector"

[direction]
source = true

[[protocol]]
name = "mqtt"


[[params]]
name = "endpoint"
description = "end point"
type = "URL"
