[package]
name = "fluvio-connectors-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.127", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.8.18"
